### ISSUE TITLE
Using shears on Dark Oak fence causes a crash

### ISSUE THREAD

**Issue by romeotheoracle** [NemoNotFound/NemosMossyBlocks#6]
Not sure why, but using shears on a normal dark oak fence causes my game to crash. This is repeatable. I've been given the following errors:

java.lang.ExceptionInInitializerError
	at knot//net.minecraft.class_1820.getShearedState(class_1820.java:590)
	at knot//net.minecraft.class_1820.tryShear(class_1820.java:578)
	at knot//net.minecraft.class_1820.handler$dgj001$nemos-mossy-blocks$useOnBlock(class_1820.java:543)
	at knot//net.minecraft.class_1820.method_7884(class_1820.java)
	at knot//net.minecraft.class_1799.method_7981(class_1799.java:388)
	at knot//net.minecraft.class_636.method_41934(class_636.java:368)
	at knot//net.minecraft.class_636.method_41933(class_636.java:320)
	at knot//net.minecraft.class_636.method_41931(class_636.java:281)
	at knot//net.minecraft.class_636.method_2896(class_636.java:319)
	at knot//net.minecraft.class_310.method_1583(class_310.java:1767)
	at knot//net.minecraft.class_310.redirect$zhi000$betterthirdperson$onDoItemUse(class_310.java:5145)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2039)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1861)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1302)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: Block{nemos-mossy-blocks:mossy_dark_oak_door}=Block{minecraft:dark_oak_door} and Block{nemos-mossy-blocks:mossy_dark_oak_door}=Block{minecraft:dark_oak_door}
	at knot//com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:382)
	at knot//com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:376)
	at knot//com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:249)
	at knot//com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:136)
	at knot//com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:98)
	at knot//com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:579)
	at knot//com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:607)
	at knot//com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:594)
	at knot//com.nemonotfound.nemosmossyblocks.block.BlockUtils.<clinit>(BlockUtils.java:487)
	... 19 more

**Comment by NemoNotFound** [comment]
Oh noo, I'll have a look. Thanks for letting me know!

**Comment by NemoNotFound** [comment]
Found the issue, will update it later!

**Comment by NemoNotFound** [comment]
I fixed it with version 1.7.1. Thanks for reporting!

**Comment by NemoNotFound** [comment]
Will close this ticket now
